name: Sync to Main Website

on:
  push:
    branches:
      - main
    paths:
      - 'uploads/**'

jobs:
  sync_files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Admin Repository
      uses: actions/checkout@v2
      with:
        repository: CompeteX001/sneha-tution-admin
        path: admin-repo

    - name: Checkout Main Website Repository
      uses: actions/checkout@v2
      with:
        repository: CompeteX001/sneha-tutions
        path: main-repo

    - name: Sync Files
      run: |
        cp -R admin-repo/uploads/* main-repo/uploads/
        cd main-repo
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m "Sync files from admin portal"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.ADMIN_TOKEN }}
